name: 'CSS Analytics Diff'
description: 'Take CSS and get the changes per CSS Analytics metric'
author: 'Bart Veneman (ProjectWallace.com)'

inputs:
  github-token:
    required: true
  project-wallace-token:
    description: 'Webhook token of the project on ProjectWallace.com'
    required: true
  css-path:
    description: 'Path to the CSS you want analyzed'
    required: true
  debug:
    description: If true, adds some additional logging
    default: false

outputs:
  hasChanged:
    description: 'Whether the CSS Analytics has changed'
  changeCount:
    description: 'How many CSS Analytics metrics have changed'
  changes:
    description: 'List of CSS Analytics metrics that have changed'

runs:
  using: 'node12'
  main: 'index.js'

branding:
  color: 'blue'
  icon: 'bar-chart-2'
